ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
ALTER TABLE "orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "reservations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tables" FORCE ROW LEVEL SECURITY;
ALTER TABLE "events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "branch_products" FORCE ROW LEVEL SECURITY;
ALTER TABLE "franchise_agreements" FORCE ROW LEVEL SECURITY;
